version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - ./gitlab/redis:/var/lib/redis:Z
    env_file: settings/redis.env

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - ./gitlab/postgresql:/var/lib/postgresql:Z
    env_file: settings/postgresql.env

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.4.1
    depends_on:
    - redis
    - postgresql
    ports:
    - "8888:80"
    - "2222:22"
#    external_links:
#    - "registry:registry.example.com"
    volumes:
    - ./gitlab/gitlab:/home/git/data:Z
    - ./logs:/var/log/gitlab
    - ./certs:/certs
    env_file : settings/gitlab.env

#  registry:
#    restart: always
#    image: registry:2.4.1
#    ports:
#    - "5000:5000"
#    volumes:
#    - ./gitlab/registry:/var/lib/registry
#    - ./certs:/certs
#    external_links:
#    - "gitlab:gitlab.example.com"
#    env_file : settings/registry.env
